### PR TITLE
added option to exclude upcoming Free Chat Streams in GetStreams()

### PR DESCRIPTION
**Pull request by brylleee**
Please let me know what you think.
If it's approved feel free to modify, especially the naming.
Thank you very much

### CODE REVIEW

**Comment by EBro912** [comment]
Will implement my own version, however consider this approved. Thanks for the idea! 😄

**Comment by brylleee** [comment]
Thank you very much!!!
However I have a small concern, sometimes there are streams titled "Midnight Talk", "Chit chat", etc. which is also a match for "(free|chat|talk)", it would also get removed from the upcoming streams

**Comment by EBro912** [comment]
That's a good point, I wonder if it should only search for the word "free", since most chat rooms are labelled as "FreeChat" or whatever...

**Comment by brylleee** [comment]
Some of them are named "chat rooms" or similar variations where either "free" or "room" is absent and theres a "ting" after "chat". The RegEx I used checks out, let me know if you thought of a better one. Cheers!

**Comment by EBro912** [comment]
I was testing your regex in a regex tester and it seemed to only pick up the word "chat" when I was testing, I dunno why it wasn't working which is why I added my own. So you're saying that the regex should pick up:
- free
- room
- chat
- ting
These four combined should cover most of them ("Free Chat", "Chat Room", "Chatting", etc). I can probably patch up the current regex with these unless you have anything else to add. Thanks!

**Comment by brylleee** [comment]
Oh that was wierd. It should pick up the word chat(ting), and then either "free" or "room". I'll recheck my RegEx, I wonder why it doesn't work. I'll give you an update!

**Comment by brylleee** [comment]
Alright, this snippet should work, I've tested it now.
```
string regex = @"(free\s){0,1}(chat(ting){0,1}|talk)(\sroom){0,1}";
upcoming.RemoveAll(stream => Regex.Match(stream.Title.ToLower(), regex).Success 
                   && Regex.Match(stream.Title.ToLower(), @"(free|room)").Success);
```

Let me know what you think 😄

**Comment by EBro912** [comment]
Looks good, I'll push an update using your Regex snippet. Tested it with a few actual streams and seemed to capture them all.

**Comment by brylleee** [comment]
Thank you so much! I didn't know what was wrong with the previous regex pattern, so sorry for the trouble!

**Comment by brylleee** [comment]
Im so sorry for making this longer than it should be but,
```&& Regex.Match(stream.Title.ToLower(), @"(free|room)").Success);```
The line above is necessary since "free" and "room" are both optional matches and we may unintentionally remove streams titled "morning chat", "chit chatting", or any variations.
The line ensures that when "free" is absent, "room" must be present and vice-versa.

Thanks again!

**Comment by EBro912** [comment]
Ah, that makes sense. To be honest I wasn't quite sure what the point of that line was, but thanks for explaining. (Admittedly I don't do much with regex so I'm still kind of learning). I'll probably add that line but wait to push it to nuget so users aren't spammed with updates. Thanks for the help!

**Comment by brylleee** [comment]
No problem, and thank you so much too!

**Pull request merged**
